version: '3.7'
services:
        mongo:
                image: mongo
                container_name: mongo
                ports:
                        - '27017:27017'
                environment:
                        MONGO_INITDB_ROOT_USERNAME: root
                        MONGO_INITDB_ROOT_PASSWORD: example
                networks:
                        iauu_net:
        mongo-express:
                image: mongo-express
                container_name: mexpress
                ports:
                        - '8081:8081'
                environment:
                        ME_CONFIG_MONGODB_ADMINUSERNAME: root
                        ME_CONFIG_MONGODB_ADMINPASSWORD: example
                networks:
                        iauu_net:
        server:
                image: node
                container_name: server
                build: ./server
                ports:
                        - '3003:3000'
                networks:
                        iauu_net:

networks:
        iauu_net:
